export 'package:asistencia_app/screens/login_screen.dart';
export 'package:asistencia_app/screens/check_auth_screen.dart';
export 'package:asistencia_app/screens/initt_screen.dart';
export 'package:asistencia_app/screens/home_screen.dart';
export 'package:asistencia_app/screens/asistencia_screen.dart';
export 'package:asistencia_app/screens/img_screen.dart';
export 'package:asistencia_app/screens/configuracion_screen.dart';
export 'package:asistencia_app/screens/perfil_screen.dart';
export 'package:asistencia_app/screens/solicitar_screen.dart';
